### Numpy

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(10, 100, 20)

In [8]:
print(type(arr), arr.size, arr.shape, arr.dtype, arr.itemsize)

<class 'numpy.ndarray'> 20 (20,) int32 4


In [9]:
print(arr)

[85 12 36 79 69 26 72 85 80 99 32 14 14 84 84 47 97 45 25 41]


In [10]:
arr[0]

85

In [11]:
arr[:5]

array([85, 12, 36, 79, 69])

In [12]:
arr[-5:]

array([47, 97, 45, 25, 41])

In [13]:
arr[::2]

array([85, 36, 69, 72, 80, 32, 14, 84, 97, 25])

In [14]:
arr[0] = 100


In [15]:
arr

array([100,  12,  36,  79,  69,  26,  72,  85,  80,  99,  32,  14,  14,
        84,  84,  47,  97,  45,  25,  41])

In [16]:
arr[-5:] = arr[:5]

In [17]:
print(arr)

[100  12  36  79  69  26  72  85  80  99  32  14  14  84  84 100  12  36
  79  69]


In [18]:
arr[[0, 1, 6, 3]]

array([100,  12,  72,  79])

In [19]:
arr > 90

array([ True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False])

In [20]:
arr[arr > 90]

array([100,  99, 100])

In [22]:
arr[ (arr > 90 ) | ( arr < 30)] # Selection

array([100,  12,  26,  99,  14,  14, 100,  12])

#### Statistical Functions

In [23]:
arr.mean()

59.1

In [24]:
np.median(arr)

70.5

In [26]:
arr.std() # sigma / standard deviation

31.497460215071307

In [27]:
arr.var() # sigma square / variance

992.0899999999999

In [28]:
np.quantile(arr, [.25, .5, .75])

array([30.5, 70.5, 84. ])

In [29]:
arr.sum()

1182

In [30]:
arr

array([100,  12,  36,  79,  69,  26,  72,  85,  80,  99,  32,  14,  14,
        84,  84, 100,  12,  36,  79,  69])

### Element wise Operations

In [31]:
data1 = arr[:5]

In [32]:
data1

array([100,  12,  36,  79,  69])

In [33]:
data1 + 1

array([101,  13,  37,  80,  70])

In [34]:
data1 * 5

array([500,  60, 180, 395, 345])

In [35]:
data1 / 6

array([16.66666667,  2.        ,  6.        , 13.16666667, 11.5       ])

In [36]:
data1

array([100,  12,  36,  79,  69])

In [39]:
data2 = arr[5: 10]

In [40]:
data1

array([100,  12,  36,  79,  69])

In [41]:
data2

array([26, 72, 85, 80, 99])

In [42]:
data1.shape == data2.shape

True

In [43]:
data1 + data2

array([126,  84, 121, 159, 168])

In [44]:
data1 * data2

array([2600,  864, 3060, 6320, 6831])

In [45]:
data1 / data2

array([3.84615385, 0.16666667, 0.42352941, 0.9875    , 0.6969697 ])

In [47]:
data1

array([100,  12,  36,  79,  69])

In [46]:
data1.cumsum()

array([100, 112, 148, 227, 296], dtype=int32)

In [49]:
data1.cumsum() / range(1, 6)

array([100.        ,  56.        ,  49.33333333,  56.75      ,
        59.2       ])

# 2-D array

In [51]:
!type data.csv

quan,price,sell price
4,6000,7500
3,500,650
10,400,450
50,1500,1660


    Practice Notebook 

In [52]:
arr = np.array([
    [30, 40, 60, 90],
    [70, 45, 23, 26],
    [13, 19, 45, 10],
    [46, 48, 50, 70]
])

In [53]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


In [54]:
print("Type: ", type(arr)) # numpy.ndarray
print("Data Type: ", arr.dtype) # int32
print("Size: ", arr.size) # 16
print("Dimensions: ", arr.ndim) # 2
print("Shape: ", arr.shape) # (4, 4)

Type:  <class 'numpy.ndarray'>
Data Type:  int32
Size:  16
Dimensions:  2
Shape:  (4, 4)


In [55]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

`syntax`

    arr[ row_index, column_index]
    
    arr[ row_slice, column_slice]

In [56]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


In [57]:
print(arr[1::2]) # ? 

[[70 45 23 26]
 [46 48 50 70]]


In [58]:
print(arr[::-1]) # ? 

[[46 48 50 70]
 [13 19 45 10]
 [70 45 23 26]
 [30 40 60 90]]


In [60]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


In [61]:
print(arr[2, 3])

10


In [62]:
print(arr[:, ::2]) # ? 

[[30 60]
 [70 23]
 [13 45]
 [46 50]]


In [63]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


write a code to prouce below output ? 

    [[45, 26],
     [19, 10]
     ]

In [65]:
arr[1, 1::2]

array([45, 26])

In [64]:
arr[1::2, 1::2]

array([[45, 26],
       [48, 70]])

In [66]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


In [68]:
arr[[1, 0, 3], [3, 1, 2]]
# ? 

array([26, 40, 50])

In [69]:
arr > 40

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [71]:
arr[arr > 40] # Flatten / 1-D Array

array([60, 90, 70, 45, 45, 46, 48, 50, 70])

In [73]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [74]:
arr[:, 1] > 40

array([False,  True, False,  True])

In [72]:
arr[arr[:, 1] > 40] # Flatten / 1-D Array
# [40, 45, 19, 48] > 40
# [False, True, False, True] # arr[1::2]
# [[70, 45, 23, 26]
#  [46, 48, 50, 70]]

array([[70, 45, 23, 26],
       [46, 48, 50, 70]])

In [75]:
arr.sum()

685

In [76]:
arr.mean()

42.8125

In [77]:
np.median(arr)

45.0

In [78]:
np.quantile(arr, [0.25, 0.5, 0.75])

array([25.25, 45.  , 52.5 ])

In [79]:
np.std(arr)

21.619489904944565

In [81]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [80]:
arr.flatten() # if you want to convert any higher dimensional array
# into one you can use flatten function

array([30, 40, 60, 90, 70, 45, 23, 26, 13, 19, 45, 10, 46, 48, 50, 70])

In [88]:
arr.flatten(order='F')

array([30, 70, 13, 46, 40, 45, 19, 48, 60, 23, 45, 50, 90, 26, 10, 70])

In [85]:
arr.flatten().reshape((4, 4))

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [87]:
arr.flatten(order='F').reshape((4, 4), order='F')

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [89]:
print(arr)

[[30 40 60 90]
 [70 45 23 26]
 [13 19 45 10]
 [46 48 50 70]]


In [90]:
arr[:, 0]

array([30, 70, 13, 46])

In [91]:
arr[:, -1]

array([90, 26, 10, 70])

In [92]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [95]:
marks = np.array([
    [60, 80, 90], # harsh
    [90, 70, 75], # madhu
    [56, 67, 78], # neha
    [80, 50, 60] # deepraj
])

In [96]:
print(marks)

[[60 80 90]
 [90 70 75]
 [56 67 78]
 [80 50 60]]


In [101]:
marks.sum(axis=1) / 3

array([76.66666667, 78.33333333, 67.        , 63.33333333])

In [102]:
marks.sum(axis=0)

array([286, 267, 303])

In [103]:
marks.mean(axis=0)

array([71.5 , 66.75, 75.75])

In [104]:
marks.mean(axis=1)

array([76.66666667, 78.33333333, 67.        , 63.33333333])

In [105]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [106]:
arr + arr

array([[ 60,  80, 120, 180],
       [140,  90,  46,  52],
       [ 26,  38,  90,  20],
       [ 92,  96, 100, 140]])

In [107]:
arr * 5

array([[150, 200, 300, 450],
       [350, 225, 115, 130],
       [ 65,  95, 225,  50],
       [230, 240, 250, 350]])

In [108]:
arr / 100

array([[0.3 , 0.4 , 0.6 , 0.9 ],
       [0.7 , 0.45, 0.23, 0.26],
       [0.13, 0.19, 0.45, 0.1 ],
       [0.46, 0.48, 0.5 , 0.7 ]])

In [110]:
arr

array([[30, 40, 60, 90],
       [70, 45, 23, 26],
       [13, 19, 45, 10],
       [46, 48, 50, 70]])

In [109]:
arr * arr

array([[ 900, 1600, 3600, 8100],
       [4900, 2025,  529,  676],
       [ 169,  361, 2025,  100],
       [2116, 2304, 2500, 4900]])

### Matrix 

In [111]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([
    [6, 5, 4],
    [3, 2, 1]
])

In [112]:
print(a)
print(b)

[[10 20 30]
 [40 50 60]]
[[6 5 4]
 [3 2 1]]


In [113]:
c = a * b
print(c)

[[ 60 100 120]
 [120 100  60]]


In [114]:
A = np.array([
    [5, 1],
    [6,3],
    [2, 4]
])

In [115]:
B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [117]:
C = A @ B # matrix multiplication

In [118]:
print(C)

[[10 16 22 28]
 [21 30 39 48]
 [22 28 34 40]]


In [119]:
np.dot(A, B) # matrix wise multiplication

array([[10, 16, 22, 28],
       [21, 30, 39, 48],
       [22, 28, 34, 40]])

In [120]:
np.matmul(A, B) # matrix wise multiplication

array([[10, 16, 22, 28],
       [21, 30, 39, 48],
       [22, 28, 34, 40]])

In [121]:
np.multiply(a, b) # element wise multiplication

array([[ 60, 100, 120],
       [120, 100,  60]])

In [122]:
np.add(a, b) # element wise addition

array([[16, 25, 34],
       [43, 52, 61]])

In [123]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [124]:
A

array([[5, 1],
       [6, 3],
       [2, 4]])

In [125]:
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
C

array([[10, 16, 22, 28],
       [21, 30, 39, 48],
       [22, 28, 34, 40]])

#### Doubt ? 

In [127]:
A = np.array([
    #A, B
    [1, 2], # India
    [3, 4]  # USA
]) # price

In [128]:
# quantity
B = np.array([
    [3, 5, 7],# India
    [4, 6, 8] # Usa
])

In [129]:
C = np.matmul(A, B) # 

In [130]:
print(C)

[[11 17 23]
 [25 39 53]]


`y = wx + c`

    woxo+w1x1+w2 ? 

#### 3-D Array

In [ ]:
size = n*m*k

In [133]:
arr = np.random.randint(10, 50, 125).reshape(5, 5, 5)

In [134]:
arr.ndim # Rank 

3

In [136]:
arr.shape

(5, 5, 5)

In [ ]:
5 records of 5x5 matrix 

In [135]:
print(arr)

[[[11 33 48 27 37]
  [44 19 44 25 30]
  [13 21 33 32 21]
  [42 19 12 40 11]
  [27 30 29 39 28]]

 [[43 31 39 45 41]
  [28 42 35 28 26]
  [23 21 34 13 11]
  [44 25 30 38 42]
  [33 29 12 18 21]]

 [[48 29 27 35 44]
  [39 31 35 10 43]
  [49 39 41 26 34]
  [43 37 19 31 34]
  [34 20 31 30 21]]

 [[18 27 29 40 47]
  [28 26 16 28 19]
  [46 38 22 32 37]
  [37 22 11 10 31]
  [10 31 37 28 25]]

 [[18 20 16 11 14]
  [28 16 33 29 13]
  [39 16 14 32 19]
  [18 23 44 40 20]
  [45 32 17 15 22]]]


In [137]:
arr[3] # 2-D array

array([[18, 27, 29, 40, 47],
       [28, 26, 16, 28, 19],
       [46, 38, 22, 32, 37],
       [37, 22, 11, 10, 31],
       [10, 31, 37, 28, 25]])

In [138]:
arr[3, 1] # ? 

array([28, 26, 16, 28, 19])

In [139]:
arr[::2, ::2, ::2]
#   record, row, column

array([[[11, 48, 37],
        [13, 33, 21],
        [27, 29, 28]],

       [[48, 27, 44],
        [49, 41, 34],
        [34, 31, 21]],

       [[18, 16, 14],
        [39, 14, 19],
        [45, 17, 22]]])

#### Array 

    np.linspace
    np.zeros
    np.ones
    np.full
    np.empty
    np.random.normal
    np.random.uniform
    np.random.binomial


    np.argmax
    np.argsort

    np.diagonal

`Stats`

#### Matplotlib

#### Pandas

In [140]:
arr = np.zeros(20).reshape(5, 4)

In [141]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
arr[0, :]  = 1
arr[:, 0]  = 1
arr[-1, :] = 1
arr[:, -1] = 1

In [143]:
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])